# 如需自定义，复制此文件为 config.yaml 进行配置
# 更新配置后需要重启

# chromium 地址，可填写系统的 edge/chromium 路径，例如（根据实际情况调整）：
# chromiumPath: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
chromiumPath:

# playwright websocket 或 cdp 地址，连接单独存在的 chromium。
# playwrightWS: 'ws://browserless:3000'
# puppeteerWS: 'ws://browserless:3000'
playwrightWS:
puppeteerWS:

# headless
headless: true

# 浏览器空闲多久后自动关闭，单位毫秒，0 表示不自动关闭
browserIdleTimeout: 300000

# browserType 目前仅支持 chromium
browserType: chromium

# playwright 启动 args，注意 args 的 -- 前缀
args:
  - --disable-gpu
  - --disable-setuid-sandbox
  - --no-sandbox
  - --no-zygote

# 截图超时时间
playwrightTimeout:
puppeteerTimeout:

# 页面 goto 时的参数
pageGotoParams:
  timeout: 120000
  waitUntil: networkidle
